export enum ActionType {
	// Book
	BOOKS_START = 'BOOKS_START',
	BOOKS_SUCCESS = 'BOOKS_SUCCESS',
	BOOKS_FAIL = 'BOOKS_FAIL',
	ADD_BOOK = 'ADD_BOOK',
	UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS',
	SET_BOOK_ACTION_LOADING = 'SET_BOOK_ACTION_LOADING',
	SET_BOOK_STATUS = 'SET_BOOK_STATUS',
	// Page
	SET_PAGE_TITLE = 'SET_PAGE_TITLE',
	// User
	USERS_START = 'USERS_START',
	USERS_SUCCESS = 'USERS_SUCCESS',
	USERS_FAIL = 'USERS_FAIL',
	ADD_USER = 'ADD_USER',
}
